baseURL = "/hi-java"
title = "Java"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableInlineShortcodes = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocLogo = "/java-logo.png"
  geekdocRepo = "https://github.com/Huauauaa/hi-java"
  geekdocEditPath = "edit/main/content"
